export const PRICE_PER_IMPRESSION_IN_DOLLARS = 0.0000085;
export const PRICE_PER_IMPRESSION_IN_EUROS = 0.0000078;
export const PRICE_PER_IMPRESSION_IN_LIVRE = 0.0000073;
export const IMPRESSION_ARIA_LABEL = "post";
export const TWEET_IMPRESSION_INDEX = 3;

export const CURRENCY_RATES = {
    '$': PRICE_PER_IMPRESSION_IN_DOLLARS,
    '€': PRICE_PER_IMPRESSION_IN_EUROS,
    '£': PRICE_PER_IMPRESSION_IN_LIVRE
};
